# Created by and for Qt Creator This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

#TARGET = EmbeddedSerialFiller

HEADERS = \
   $$PWD/etl/include/etl/atomic/atomic_arm.h \
   $$PWD/etl/include/etl/atomic/atomic_gcc_sync.h \
   $$PWD/etl/include/etl/atomic/atomic_llvm_sync.h \
   $$PWD/etl/include/etl/atomic/atomic_std.h \
   $$PWD/etl/include/etl/c/ecl_timer.h \
   $$PWD/etl/include/etl/deprecated/factory.h \
   $$PWD/etl/include/etl/experimental/atomic.h \
   $$PWD/etl/include/etl/mutex/mutex_arm.h \
   $$PWD/etl/include/etl/mutex/mutex_gcc_sync.h \
   $$PWD/etl/include/etl/mutex/mutex_std.h \
   $$PWD/etl/include/etl/private/ivectorpointer.h \
   $$PWD/etl/include/etl/private/minmax_pop.h \
   $$PWD/etl/include/etl/private/minmax_push.h \
   $$PWD/etl/include/etl/private/pvoidvector.h \
   $$PWD/etl/include/etl/private/to_string_helper.h \
   $$PWD/etl/include/etl/private/vector_base.h \
   $$PWD/etl/include/etl/profiles/arduino_arm.h \
   $$PWD/etl/include/etl/profiles/armv5.h \
   $$PWD/etl/include/etl/profiles/armv5_no_stl.h \
   $$PWD/etl/include/etl/profiles/armv6.h \
   $$PWD/etl/include/etl/profiles/armv6_no_stl.h \
   $$PWD/etl/include/etl/profiles/clang_generic.h \
   $$PWD/etl/include/etl/profiles/cpp03.h \
   $$PWD/etl/include/etl/profiles/cpp03_no_stl.h \
   $$PWD/etl/include/etl/profiles/cpp11.h \
   $$PWD/etl/include/etl/profiles/cpp11_no_stl.h \
   $$PWD/etl/include/etl/profiles/cpp14.h \
   $$PWD/etl/include/etl/profiles/cpp14_no_stl.h \
   $$PWD/etl/include/etl/profiles/cpp17.h \
   $$PWD/etl/include/etl/profiles/cpp17_no_stl.h \
   $$PWD/etl/include/etl/profiles/etl_profile.h \
   $$PWD/etl/include/etl/profiles/gcc_generic.h \
   $$PWD/etl/include/etl/profiles/gcc_linux_x86.h \
   $$PWD/etl/include/etl/profiles/gcc_windows_x86.h \
   $$PWD/etl/include/etl/profiles/msvc_x86.h \
   $$PWD/etl/include/etl/profiles/segger_gcc_stlport.h \
   $$PWD/etl/include/etl/profiles/ticc.h \
   $$PWD/etl/include/etl/stl/alternate/algorithm.h \
   $$PWD/etl/include/etl/stl/alternate/functional.h \
   $$PWD/etl/include/etl/stl/alternate/iterator.h \
   $$PWD/etl/include/etl/stl/alternate/limits.h \
   $$PWD/etl/include/etl/stl/alternate/utility.h \
   $$PWD/etl/include/etl/stl/algorithm.h \
   $$PWD/etl/include/etl/stl/functional.h \
   $$PWD/etl/include/etl/stl/iterator.h \
   $$PWD/etl/include/etl/stl/limits.h \
   $$PWD/etl/include/etl/stl/utility.h \
   $$PWD/etl/include/etl/absolute.h \
   $$PWD/etl/include/etl/algorithm.h \
   $$PWD/etl/include/etl/alignment.h \
   $$PWD/etl/include/etl/array.h \
   $$PWD/etl/include/etl/array_view.h \
   $$PWD/etl/include/etl/array_wrapper.h \
   $$PWD/etl/include/etl/atomic.h \
   $$PWD/etl/include/etl/basic_format_spec.h \
   $$PWD/etl/include/etl/basic_string.h \
   $$PWD/etl/include/etl/binary.h \
   $$PWD/etl/include/etl/bit_stream.h \
   $$PWD/etl/include/etl/bitset.h \
   $$PWD/etl/include/etl/bloom_filter.h \
   $$PWD/etl/include/etl/callback.h \
   $$PWD/etl/include/etl/callback_service.h \
   $$PWD/etl/include/etl/callback_timer.h \
   $$PWD/etl/include/etl/char_traits.h \
   $$PWD/etl/include/etl/checksum.h \
   $$PWD/etl/include/etl/combinations.h \
   $$PWD/etl/include/etl/compare.h \
   $$PWD/etl/include/etl/constant.h \
   $$PWD/etl/include/etl/container.h \
   $$PWD/etl/include/etl/crc16.h \
   $$PWD/etl/include/etl/crc16_ccitt.h \
   $$PWD/etl/include/etl/crc16_kermit.h \
   $$PWD/etl/include/etl/crc16_modbus.h \
   $$PWD/etl/include/etl/crc32.h \
   $$PWD/etl/include/etl/crc32_c.h \
   $$PWD/etl/include/etl/crc64_ecma.h \
   $$PWD/etl/include/etl/crc8_ccitt.h \
   $$PWD/etl/include/etl/cstring.h \
   $$PWD/etl/include/etl/cumulative_moving_average.h \
   $$PWD/etl/include/etl/cyclic_value.h \
   $$PWD/etl/include/etl/debounce.h \
   $$PWD/etl/include/etl/debug_count.h \
   $$PWD/etl/include/etl/delegate.h \
   $$PWD/etl/include/etl/delegate_service.h \
   $$PWD/etl/include/etl/deque.h \
   $$PWD/etl/include/etl/doxygen.h \
   $$PWD/etl/include/etl/endianness.h \
   $$PWD/etl/include/etl/enum_type.h \
   $$PWD/etl/include/etl/error_handler.h \
   $$PWD/etl/include/etl/exception.h \
   $$PWD/etl/include/etl/factorial.h \
   $$PWD/etl/include/etl/fibonacci.h \
   $$PWD/etl/include/etl/fixed_iterator.h \
   $$PWD/etl/include/etl/flat_map.h \
   $$PWD/etl/include/etl/flat_multimap.h \
   $$PWD/etl/include/etl/flat_multiset.h \
   $$PWD/etl/include/etl/flat_set.h \
   $$PWD/etl/include/etl/fnv_1.h \
   $$PWD/etl/include/etl/format_spec.h \
   $$PWD/etl/include/etl/forward_list.h \
   $$PWD/etl/include/etl/frame_check_sequence.h \
   $$PWD/etl/include/etl/fsm.h \
   $$PWD/etl/include/etl/fsm_generator.h \
   $$PWD/etl/include/etl/function.h \
   $$PWD/etl/include/etl/functional.h \
   $$PWD/etl/include/etl/hash.h \
   $$PWD/etl/include/etl/icache.h \
   $$PWD/etl/include/etl/ihash.h \
   $$PWD/etl/include/etl/instance_count.h \
   $$PWD/etl/include/etl/integral_limits.h \
   $$PWD/etl/include/etl/intrusive_forward_list.h \
   $$PWD/etl/include/etl/intrusive_links.h \
   $$PWD/etl/include/etl/intrusive_list.h \
   $$PWD/etl/include/etl/intrusive_queue.h \
   $$PWD/etl/include/etl/intrusive_stack.h \
   $$PWD/etl/include/etl/io_port.h \
   $$PWD/etl/include/etl/iterator.h \
   $$PWD/etl/include/etl/jenkins.h \
   $$PWD/etl/include/etl/largest.h \
   $$PWD/etl/include/etl/largest_generator.h \
   $$PWD/etl/include/etl/list.h \
   $$PWD/etl/include/etl/log.h \
   $$PWD/etl/include/etl/macros.h \
   $$PWD/etl/include/etl/map.h \
   $$PWD/etl/include/etl/math_constants.h \
   $$PWD/etl/include/etl/memory.h \
   $$PWD/etl/include/etl/memory_model.h \
   $$PWD/etl/include/etl/message.h \
   $$PWD/etl/include/etl/message_bus.h \
   $$PWD/etl/include/etl/message_router.h \
   $$PWD/etl/include/etl/message_router_generator.h \
   $$PWD/etl/include/etl/message_timer.h \
   $$PWD/etl/include/etl/message_types.h \
   $$PWD/etl/include/etl/multi_array.h \
   $$PWD/etl/include/etl/multicast_delegate.h \
   $$PWD/etl/include/etl/multimap.h \
   $$PWD/etl/include/etl/multiset.h \
   $$PWD/etl/include/etl/murmur3.h \
   $$PWD/etl/include/etl/mutex.h \
   $$PWD/etl/include/etl/negative.h \
   $$PWD/etl/include/etl/null_type.h \
   $$PWD/etl/include/etl/nullptr.h \
   $$PWD/etl/include/etl/numeric.h \
   $$PWD/etl/include/etl/observer.h \
   $$PWD/etl/include/etl/optional.h \
   $$PWD/etl/include/etl/packet.h \
   $$PWD/etl/include/etl/parameter_type.h \
   $$PWD/etl/include/etl/pearson.h \
   $$PWD/etl/include/etl/permutations.h \
   $$PWD/etl/include/etl/platform.h \
   $$PWD/etl/include/etl/pool.h \
   $$PWD/etl/include/etl/power.h \
   $$PWD/etl/include/etl/priority_queue.h \
   $$PWD/etl/include/etl/queue.h \
   $$PWD/etl/include/etl/queue_mpmc_mutex.h \
   $$PWD/etl/include/etl/queue_spsc_atomic.h \
   $$PWD/etl/include/etl/queue_spsc_isr.h \
   $$PWD/etl/include/etl/queue_spsc_locked.h \
   $$PWD/etl/include/etl/radix.h \
   $$PWD/etl/include/etl/random.h \
   $$PWD/etl/include/etl/ratio.h \
   $$PWD/etl/include/etl/reference_flat_map.h \
   $$PWD/etl/include/etl/reference_flat_multimap.h \
   $$PWD/etl/include/etl/reference_flat_multiset.h \
   $$PWD/etl/include/etl/reference_flat_set.h \
   $$PWD/etl/include/etl/scaled_rounding.h \
   $$PWD/etl/include/etl/scheduler.h \
   $$PWD/etl/include/etl/set.h \
   $$PWD/etl/include/etl/smallest.h \
   $$PWD/etl/include/etl/smallest_generator.h \
   $$PWD/etl/include/etl/spsc_queue.h \
   $$PWD/etl/include/etl/sqrt.h \
   $$PWD/etl/include/etl/stack.h \
   $$PWD/etl/include/etl/state_chart.h \
   $$PWD/etl/include/etl/static_assert.h \
   $$PWD/etl/include/etl/string_view.h \
   $$PWD/etl/include/etl/task.h \
   $$PWD/etl/include/etl/temp.h \
   $$PWD/etl/include/etl/timer.h \
   $$PWD/etl/include/etl/to_string.h \
   $$PWD/etl/include/etl/to_u16string.h \
   $$PWD/etl/include/etl/to_u32string.h \
   $$PWD/etl/include/etl/to_wstring.h \
   $$PWD/etl/include/etl/type_def.h \
   $$PWD/etl/include/etl/type_lookup.h \
   $$PWD/etl/include/etl/type_lookup_generator.h \
   $$PWD/etl/include/etl/type_select.h \
   $$PWD/etl/include/etl/type_select_generator.h \
   $$PWD/etl/include/etl/type_traits.h \
   $$PWD/etl/include/etl/type_traits_generator.h \
   $$PWD/etl/include/etl/u16format_spec.h \
   $$PWD/etl/include/etl/u16string.h \
   $$PWD/etl/include/etl/u32format_spec.h \
   $$PWD/etl/include/etl/u32string.h \
   $$PWD/etl/include/etl/unordered_map.h \
   $$PWD/etl/include/etl/unordered_multimap.h \
   $$PWD/etl/include/etl/unordered_multiset.h \
   $$PWD/etl/include/etl/unordered_set.h \
   $$PWD/etl/include/etl/user_type.h \
   $$PWD/etl/include/etl/utility.h \
   $$PWD/etl/include/etl/variant.h \
   $$PWD/etl/include/etl/variant_pool.h \
   $$PWD/etl/include/etl/variant_pool_generator.h \
   $$PWD/etl/include/etl/vector.h \
   $$PWD/etl/include/etl/version.h \
   $$PWD/etl/include/etl/visitor.h \
   $$PWD/etl/include/etl/wformat_spec.h \
   $$PWD/etl/include/etl/wstring.h \
   $$PWD/etl/temp/message_router.h \
   $$PWD/include/SerialFiller/Exceptions/CobsDecodingFailed.hpp \
   $$PWD/include/SerialFiller/Exceptions/CrcCheckFailed.hpp \
   $$PWD/include/SerialFiller/Exceptions/LengthOfTopicTooLong.hpp \
   $$PWD/include/SerialFiller/Exceptions/NotEnoughBytes.hpp \
   $$PWD/include/SerialFiller/Exceptions/SerialFillerException.hpp \
   $$PWD/include/SerialFiller/CobsTranscoder.hpp \
   $$PWD/include/SerialFiller/Constants.hpp \
   $$PWD/include/SerialFiller/Definitions.hpp \
   $$PWD/include/SerialFiller/Logger.hpp \
   $$PWD/include/SerialFiller/SerialFiller.hpp \
   $$PWD/include/SerialFiller/SerialFillerHelper.hpp \
   $$PWD/include/SerialFiller/String.hpp \
   $$PWD/include/etl_profile.h \
   $$PWD/include/gcc_linux_x86.h \
   $$PWD/include/msvc_x86.h \
   $$PWD/test/integration/Node.hpp \
   $$PWD/test/integration/ThreadSafeQ.hpp

SOURCES = \
   $$PWD/etl/src/c/ecl_timer.c \
   $$PWD/src/CobsTranscoder.cpp \
   $$PWD/src/Logger.cpp \
   $$PWD/src/SerialFiller.cpp \
   $$PWD/src/SerialFillerHelper.cpp \
   $$PWD/test/integration/TwoNodeAckTests.cpp \
   $$PWD/test/AddAndVerifyCrcTests.cpp \
   $$PWD/test/CallbackTests.cpp \
   $$PWD/test/CobsEncodeDecodeTests.cpp \
   $$PWD/test/GiveRxDataExceptionTests.cpp \
   $$PWD/test/LoopBackTests.cpp \
   $$PWD/test/main.cpp \
   $$PWD/test/NoSubscribersTests.cpp \
   $$PWD/test/PacketizeTests.cpp \
   $$PWD/test/SplitPacketTests.cpp \
   test/CrcTests.cpp

INCLUDEPATH = \
    $$PWD/etl/include \
    $$PWD/etl/include/etl \
    $$PWD/etl/include/etl/atomic \
    $$PWD/etl/include/etl/c \
    $$PWD/etl/include/etl/deprecated \
    $$PWD/etl/include/etl/experimental \
    $$PWD/etl/include/etl/mutex \
    $$PWD/etl/include/etl/private \
    $$PWD/etl/include/etl/profiles \
    $$PWD/etl/include/etl/stl \
    $$PWD/etl/include/etl/stl/alternate \
    $$PWD/etl/temp \
    $$PWD/include

#DEFINES = 

